/*
 * This source file was generated by the Gradle 'init' task
 */
package helloworld;

class Prompt extends Sysnet{
    Prompt(Sysnet.Config config){
        super(config);
    }

    protected void onGranted(Object data){
        System.out.print("granted");
    }
}

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static Sysnet.Config config = new Sysnet.Config();

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        config.credentials = new Sysnet.Credentials();
        config.credentials.address = "hello.getstarted.java.tdpnet.4da";
        config.credentials.accesskey = "000450";
        config.credentials.password = "1af241ed-41e6-49ed-9e04-116b9dc38ee7";
        config.host = "http://217.76.52.255:20000";

        config.peers = new Sysnet.Peers();
        config.peers.greeter = "greeter.getstarted.tdpnet.4da";

        Prompt prompt = new Prompt(config);
    }
}
