/*
 * This source file was generated by the Gradle 'init' task
 */
package helloworld;

import tdpnet.Session;

class Prompt extends Session{
    Prompt(){

    }

    protected void onConnected(long timestamp){
        System.out.println("connected");
    }

    protected void onGranted(Object data){
        System.out.print("granted");
    }
}

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Prompt prompt = new Prompt();
        prompt.connect("http://217.76.52.255:20000");
    }
}
