/*
 * This source file was generated by the Gradle 'init' task
 */
package hello;

import tdpnet.*;

import java.io.*;
import java.util.HashMap;
import java.util.Map;

class Prompt extends Sysnet{
    public Prompt(Config config){
        super(config);
    }

    @Override
    protected void onGranted(Object data) {
        System.out.println("granted!");

        this.request(this.peers.greeter, "{}");
    }

    @Override
    protected void onResponse(Message msg) {
        System.out.println(String.format("%s %s %s",msg.from, msg.timestamp,  msg.detail));
        
        this.request(msg.from, "{}");
    }

}

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        String host = "http://217.76.52.255:20000";
        Peers peers = new Peers("greeter.getstarted.tdpnet.4da");

        //Use the credentials here:
        Credentials credentials = new Credentials("ACCESSKEY", "PASSWORD", "ADDRESS");

        Config config = new Config(host, peers, credentials);

        new Prompt(config);
    }
}
