/*
 * This source file was generated by the Gradle 'init' task
 */
package hello;

import tdpnet.*;

import java.io.*;
import java.util.HashMap;
import java.util.Map;

class Prompt extends Sysnet{
    public Prompt(Config config){
        super(config);
    }

    @Override
    protected void onGranted(Object data) {
        System.out.println("granted!");

        this.request(this.peers.greeter, "{}");
    }

    @Override
    protected void onResponse(Message msg) {
        System.out.println(String.format("%s %s %s",msg.from, msg.timestamp,  msg.detail));
        
        this.request(msg.from, "{}");
    }

}

public class App {
    public static void main(String[] args) throws Exception {

        new Prompt(new Config());
        
    }
}
